Document: rtpinsertsound
Title: Debian rtpinsertsound Manual
Author: <insert document author here>
Abstract: This manual describes what rtpinsertsound is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtpinsertsound/rtpinsertsound.sgml.gz

Format: postscript
Files: /usr/share/doc/rtpinsertsound/rtpinsertsound.ps.gz

Format: text
Files: /usr/share/doc/rtpinsertsound/rtpinsertsound.text.gz

Format: HTML
Index: /usr/share/doc/rtpinsertsound/html/index.html
Files: /usr/share/doc/rtpinsertsound/html/*.html
